var config = {
    // 默认的服务地址
    defaultServiceUrl: "http://192.168.8.204:8010/Portal/m.asmx",
    defaultAppName: "H3 BPM移动办公",
    // 默认的语言 zh_cn：中文 en_us：English
    defaultLanguage: 'zh_cn',
    // 默认是否自动登录
    defaultAutoLogin: true,
    // 是否允许修改服务器地址
    defaultAllowModifyService: true,
    // 待办是否显示排序
    defaultUnfinishedWorkItemSortable: false,
    // 默认的用户头像
    defaultImageUrl: "img/user.jpg",
    // 发起流程是否可见
    defaultStartworkflowDisplay: true,
    // 客户端类型
    platform: ["Android", "iOS"],
    //客户端平台:App,微信，钉钉
    loginfrom: "",
    portalroot: "portal",
    // 语言包
    languages: {
        current: {},
        zh: {
            isShow: false,
            back: '返回',
            close: '关闭',
            moreData: '数据加载中...',
            pullingtext: '松开刷新',
            refreshingtext: '努力加载中...',
            filter: '筛选',
            receiveTime: '接收时间：',
            handleTime: '处理时间：',
            cancelTime: '取消时间：',
            noMoreDatas: '没有更多的数据',
            sampleData: '样例数据',
            checkNetWork: '您处于离线状态，请检查网络',
            loginAgin: '登录超时，请重新登录',
            loginExit: '登录超时，即将退出',
            loginFail: '登录失败，请联系管理员',
            serverError: '远程服务器连接错误，请稍后再试',
            personTotal: '人',
            setSuccess: '设置成功',
            setFailed: '设置失败',
            ipError: 'ip不合法',
            reset: '重置',
            confirm: '确定',
            loginOut: '退出',
            checkNewVersion: '检测到新版本',
            enterUserName: '请输入账号',
            enterPassword: '请输入密码',
            loginError: '账号或密码不对！',
            tabs: {
                home: '首页',
                InitiateProcess: '发起流程',
                myProcess: '我的流程',
            },
            tabHome: {
                tab: ['待办', '待阅', '已办', '已阅'],
                setting:'设置',
            },
            tabMyInstances: {
                tab: ['常用', '全部'],
                setFrequent: '设置常用成功',
                cancelFrequent: '取消常用成功',
                searchProcessname: '搜索流程名称',
            },
            tabMyProcess: {
                tab: ['进行中', '已完成', '已取消'],
            },
            Filter: {
                processName: '流程名称',
                processNames: '请输入流程名称',
                originator: '发起人',
                createdTime: '创建日期',
                star: '初始时间',
                end: '结束时间',
                urgent: '是否加急',
                yes: '是',
                no: '否',
                all: '不限',
            },
            setting: {
                currentVersion: '当前版本',
                IP: 'IP/域名',
                languageSetting: '切换语言',
                systemSetting: '系统设置',
            },
            login: {
                antoLoading: '自动登录',
                systemSetting: '系统设置',
                Loading: '登录',
                name: '请输入账号',
                password: '请输入密码',
            },
            sheetUser: {
                organnizationName: '发起人',
                organnization: '组织机构',
                departmentStaff: '本部门',
                search: '搜索',
                checkAll: '全选',
                user: '人员',
                result: '',
            },
        },
        en: {
            isShow: true,
            back: 'Back',
            close: 'Close',
            moreData: 'Data loading…',
            pullingtext: 'Refresh after release',
            refreshingtext: 'Refreshing...',
            filter: 'Filter',
            receiveTime: 'ReceiveTime：',
            handleTime: 'HandleTime：',
            cancelTime: 'CancelTime：',
            noMoreDatas: 'No more datas',
            sampleData: 'sampleData',
            reset: 'Reset',
            confirm: 'Confirm',
            loginOut: 'LogOut',
            setFailed: 'Set failed',
            setSuccess: 'Set successfully',
            ipError:'Illegal IP',
            checkNetWork: 'You are offline，please check the network',
            loginAgin: 'Login timeout，Please login again',
            loginExit: 'Login timeout，exit',
            personTotal: 'person in total',
            serverError: 'Remote server connection error，please try again later',
            loginFail: 'Login fail，please contact the administrator',
            enterUserName: 'Please enter the userName',
            enterPassword: 'Please enter the password',
            checkNewVersion: 'detect the new version',
            loginError: 'Incorrect username or password',
            tabs: {
                home: 'HomePage',
                InitiateProcess: 'Initiate process',
                myProcess: 'My process',
            },
            tabHome: {
                tab: ['To-do task', 'To-read task', 'Finished task', 'Finished read'],
                setting: 'Setting',
            },
            tabMyInstances: {
                tab: ['Frequent Flow', 'All'],
                setFrequent: 'Set up frequent flow succeed',
                cancelFrequent: 'Cancel frequent flow succeed',
                searchProcessname:'Search processname',
            },
            tabMyProcess: {
                tab: ['Unfinished', 'Finished', 'Canceled'],
            },
            Filter: {
                processName: 'ProcessName',
                processNames: 'ProcessName please',
                originator: 'Originator',
                createdTime: 'CreatedTime',
                star: 'Initial Time',
                end: 'Endtime',
                urgent: 'Urgent',
                yes: 'Yes',
                no: 'No',
                all: 'All',
            },
            setting: {
                currentVersion: 'Current version',
                IP: 'IP/Domain Name',
                languageSetting: 'Language setting',
                systemSetting: 'System setting',
            },
            login: {
                antoLoading: 'Auto',
                systemSetting: 'System setting',
                Loading: 'Login',
                name: 'UserName',
                password: 'Password',
            },
            sheetUser: {
                organnization: 'Organnization',
                departmentStaff: 'Department Staff',
                search: 'Search',
                checkAll: 'Check all',
                user: 'Personnel',
                result: 'No results related to',
                organnizationName: 'Originator',
            },
        }
    }

}