//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace postJXSFKBL.DzService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DZBIZServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DataItemParam[]))]
    public partial class DZBIZService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BizAutoAssignOperationCompleted;
        
        private System.Threading.SendOrPostCallback BizAutoAssignHistoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancelInstanceDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateInstanceDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback finishedInstanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback postDZJROperationCompleted;
        
        private Authentication authenticationValueField;
        
        private System.Threading.SendOrPostCallback StartWorkFlowWidthValuesOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateWorkFlowDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetSigleItemValuesOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetItemValuesOperationCompleted;
        
        private System.Threading.SendOrPostCallback StartWorkflowOperationCompleted;
        
        private System.Threading.SendOrPostCallback postHttpOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DZBIZService() {
            this.Url = global::postJXSFKBL.Properties.Settings.Default.postJXSFKBL_DzService_DZBIZService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public Authentication AuthenticationValue {
            get {
                return this.authenticationValueField;
            }
            set {
                this.authenticationValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BizAutoAssignCompletedEventHandler BizAutoAssignCompleted;
        
        /// <remarks/>
        public event BizAutoAssignHistoryCompletedEventHandler BizAutoAssignHistoryCompleted;
        
        /// <remarks/>
        public event cancelInstanceDataCompletedEventHandler cancelInstanceDataCompleted;
        
        /// <remarks/>
        public event updateInstanceDataCompletedEventHandler updateInstanceDataCompleted;
        
        /// <remarks/>
        public event finishedInstanceCompletedEventHandler finishedInstanceCompleted;
        
        /// <remarks/>
        public event postDZJRCompletedEventHandler postDZJRCompleted;
        
        /// <remarks/>
        public event StartWorkFlowWidthValuesCompletedEventHandler StartWorkFlowWidthValuesCompleted;
        
        /// <remarks/>
        public event updateWorkFlowDataCompletedEventHandler updateWorkFlowDataCompleted;
        
        /// <remarks/>
        public event SetSigleItemValuesCompletedEventHandler SetSigleItemValuesCompleted;
        
        /// <remarks/>
        public event SetItemValuesCompletedEventHandler SetItemValuesCompleted;
        
        /// <remarks/>
        public event StartWorkflowCompletedEventHandler StartWorkflowCompleted;
        
        /// <remarks/>
        public event postHttpCompletedEventHandler postHttpCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BizAutoAssign", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BizAutoAssign(string instanceID, string activeCode, string cyz, string amount) {
            object[] results = this.Invoke("BizAutoAssign", new object[] {
                        instanceID,
                        activeCode,
                        cyz,
                        amount});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BizAutoAssignAsync(string instanceID, string activeCode, string cyz, string amount) {
            this.BizAutoAssignAsync(instanceID, activeCode, cyz, amount, null);
        }
        
        /// <remarks/>
        public void BizAutoAssignAsync(string instanceID, string activeCode, string cyz, string amount, object userState) {
            if ((this.BizAutoAssignOperationCompleted == null)) {
                this.BizAutoAssignOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBizAutoAssignOperationCompleted);
            }
            this.InvokeAsync("BizAutoAssign", new object[] {
                        instanceID,
                        activeCode,
                        cyz,
                        amount}, this.BizAutoAssignOperationCompleted, userState);
        }
        
        private void OnBizAutoAssignOperationCompleted(object arg) {
            if ((this.BizAutoAssignCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BizAutoAssignCompleted(this, new BizAutoAssignCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BizAutoAssignHistory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BizAutoAssignHistory(string instanceID, string activeCode, string cyz, string amount) {
            object[] results = this.Invoke("BizAutoAssignHistory", new object[] {
                        instanceID,
                        activeCode,
                        cyz,
                        amount});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BizAutoAssignHistoryAsync(string instanceID, string activeCode, string cyz, string amount) {
            this.BizAutoAssignHistoryAsync(instanceID, activeCode, cyz, amount, null);
        }
        
        /// <remarks/>
        public void BizAutoAssignHistoryAsync(string instanceID, string activeCode, string cyz, string amount, object userState) {
            if ((this.BizAutoAssignHistoryOperationCompleted == null)) {
                this.BizAutoAssignHistoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBizAutoAssignHistoryOperationCompleted);
            }
            this.InvokeAsync("BizAutoAssignHistory", new object[] {
                        instanceID,
                        activeCode,
                        cyz,
                        amount}, this.BizAutoAssignHistoryOperationCompleted, userState);
        }
        
        private void OnBizAutoAssignHistoryOperationCompleted(object arg) {
            if ((this.BizAutoAssignHistoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BizAutoAssignHistoryCompleted(this, new BizAutoAssignHistoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cancelInstanceData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string cancelInstanceData(string instanceID, string workflowCode) {
            object[] results = this.Invoke("cancelInstanceData", new object[] {
                        instanceID,
                        workflowCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void cancelInstanceDataAsync(string instanceID, string workflowCode) {
            this.cancelInstanceDataAsync(instanceID, workflowCode, null);
        }
        
        /// <remarks/>
        public void cancelInstanceDataAsync(string instanceID, string workflowCode, object userState) {
            if ((this.cancelInstanceDataOperationCompleted == null)) {
                this.cancelInstanceDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelInstanceDataOperationCompleted);
            }
            this.InvokeAsync("cancelInstanceData", new object[] {
                        instanceID,
                        workflowCode}, this.cancelInstanceDataOperationCompleted, userState);
        }
        
        private void OncancelInstanceDataOperationCompleted(object arg) {
            if ((this.cancelInstanceDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelInstanceDataCompleted(this, new cancelInstanceDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateInstanceData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string updateInstanceData(string instanceID, string workflowCode) {
            object[] results = this.Invoke("updateInstanceData", new object[] {
                        instanceID,
                        workflowCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void updateInstanceDataAsync(string instanceID, string workflowCode) {
            this.updateInstanceDataAsync(instanceID, workflowCode, null);
        }
        
        /// <remarks/>
        public void updateInstanceDataAsync(string instanceID, string workflowCode, object userState) {
            if ((this.updateInstanceDataOperationCompleted == null)) {
                this.updateInstanceDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateInstanceDataOperationCompleted);
            }
            this.InvokeAsync("updateInstanceData", new object[] {
                        instanceID,
                        workflowCode}, this.updateInstanceDataOperationCompleted, userState);
        }
        
        private void OnupdateInstanceDataOperationCompleted(object arg) {
            if ((this.updateInstanceDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateInstanceDataCompleted(this, new updateInstanceDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/finishedInstance", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string finishedInstance(string instanceID) {
            object[] results = this.Invoke("finishedInstance", new object[] {
                        instanceID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void finishedInstanceAsync(string instanceID) {
            this.finishedInstanceAsync(instanceID, null);
        }
        
        /// <remarks/>
        public void finishedInstanceAsync(string instanceID, object userState) {
            if ((this.finishedInstanceOperationCompleted == null)) {
                this.finishedInstanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfinishedInstanceOperationCompleted);
            }
            this.InvokeAsync("finishedInstance", new object[] {
                        instanceID}, this.finishedInstanceOperationCompleted, userState);
        }
        
        private void OnfinishedInstanceOperationCompleted(object arg) {
            if ((this.finishedInstanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.finishedInstanceCompleted(this, new finishedInstanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/postDZJR", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string postDZJR(string type, string url) {
            object[] results = this.Invoke("postDZJR", new object[] {
                        type,
                        url});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void postDZJRAsync(string type, string url) {
            this.postDZJRAsync(type, url, null);
        }
        
        /// <remarks/>
        public void postDZJRAsync(string type, string url, object userState) {
            if ((this.postDZJROperationCompleted == null)) {
                this.postDZJROperationCompleted = new System.Threading.SendOrPostCallback(this.OnpostDZJROperationCompleted);
            }
            this.InvokeAsync("postDZJR", new object[] {
                        type,
                        url}, this.postDZJROperationCompleted, userState);
        }
        
        private void OnpostDZJROperationCompleted(object arg) {
            if ((this.postDZJRCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.postDZJRCompleted(this, new postDZJRCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StartWorkFlowWidthValues", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string StartWorkFlowWidthValues(string WorkFlowCode, string UserCode, string JsonStr) {
            object[] results = this.Invoke("StartWorkFlowWidthValues", new object[] {
                        WorkFlowCode,
                        UserCode,
                        JsonStr});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void StartWorkFlowWidthValuesAsync(string WorkFlowCode, string UserCode, string JsonStr) {
            this.StartWorkFlowWidthValuesAsync(WorkFlowCode, UserCode, JsonStr, null);
        }
        
        /// <remarks/>
        public void StartWorkFlowWidthValuesAsync(string WorkFlowCode, string UserCode, string JsonStr, object userState) {
            if ((this.StartWorkFlowWidthValuesOperationCompleted == null)) {
                this.StartWorkFlowWidthValuesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStartWorkFlowWidthValuesOperationCompleted);
            }
            this.InvokeAsync("StartWorkFlowWidthValues", new object[] {
                        WorkFlowCode,
                        UserCode,
                        JsonStr}, this.StartWorkFlowWidthValuesOperationCompleted, userState);
        }
        
        private void OnStartWorkFlowWidthValuesOperationCompleted(object arg) {
            if ((this.StartWorkFlowWidthValuesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StartWorkFlowWidthValuesCompleted(this, new StartWorkFlowWidthValuesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateWorkFlowData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string updateWorkFlowData(string WorkFlowCode, string UserCode, string JsonStr, string instanceid) {
            object[] results = this.Invoke("updateWorkFlowData", new object[] {
                        WorkFlowCode,
                        UserCode,
                        JsonStr,
                        instanceid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void updateWorkFlowDataAsync(string WorkFlowCode, string UserCode, string JsonStr, string instanceid) {
            this.updateWorkFlowDataAsync(WorkFlowCode, UserCode, JsonStr, instanceid, null);
        }
        
        /// <remarks/>
        public void updateWorkFlowDataAsync(string WorkFlowCode, string UserCode, string JsonStr, string instanceid, object userState) {
            if ((this.updateWorkFlowDataOperationCompleted == null)) {
                this.updateWorkFlowDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateWorkFlowDataOperationCompleted);
            }
            this.InvokeAsync("updateWorkFlowData", new object[] {
                        WorkFlowCode,
                        UserCode,
                        JsonStr,
                        instanceid}, this.updateWorkFlowDataOperationCompleted, userState);
        }
        
        private void OnupdateWorkFlowDataOperationCompleted(object arg) {
            if ((this.updateWorkFlowDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateWorkFlowDataCompleted(this, new updateWorkFlowDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetSigleItemValues", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SetSigleItemValues(string bizObjectSchemaCode, string bizObjectId, string ItemName, string ItemValue) {
            object[] results = this.Invoke("SetSigleItemValues", new object[] {
                        bizObjectSchemaCode,
                        bizObjectId,
                        ItemName,
                        ItemValue});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SetSigleItemValuesAsync(string bizObjectSchemaCode, string bizObjectId, string ItemName, string ItemValue) {
            this.SetSigleItemValuesAsync(bizObjectSchemaCode, bizObjectId, ItemName, ItemValue, null);
        }
        
        /// <remarks/>
        public void SetSigleItemValuesAsync(string bizObjectSchemaCode, string bizObjectId, string ItemName, string ItemValue, object userState) {
            if ((this.SetSigleItemValuesOperationCompleted == null)) {
                this.SetSigleItemValuesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetSigleItemValuesOperationCompleted);
            }
            this.InvokeAsync("SetSigleItemValues", new object[] {
                        bizObjectSchemaCode,
                        bizObjectId,
                        ItemName,
                        ItemValue}, this.SetSigleItemValuesOperationCompleted, userState);
        }
        
        private void OnSetSigleItemValuesOperationCompleted(object arg) {
            if ((this.SetSigleItemValuesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetSigleItemValuesCompleted(this, new SetSigleItemValuesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetItemValues", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SetItemValues(string bizObjectSchemaCode, string bizObjectId, DataItemParam[] keyValues) {
            object[] results = this.Invoke("SetItemValues", new object[] {
                        bizObjectSchemaCode,
                        bizObjectId,
                        keyValues});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SetItemValuesAsync(string bizObjectSchemaCode, string bizObjectId, DataItemParam[] keyValues) {
            this.SetItemValuesAsync(bizObjectSchemaCode, bizObjectId, keyValues, null);
        }
        
        /// <remarks/>
        public void SetItemValuesAsync(string bizObjectSchemaCode, string bizObjectId, DataItemParam[] keyValues, object userState) {
            if ((this.SetItemValuesOperationCompleted == null)) {
                this.SetItemValuesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetItemValuesOperationCompleted);
            }
            this.InvokeAsync("SetItemValues", new object[] {
                        bizObjectSchemaCode,
                        bizObjectId,
                        keyValues}, this.SetItemValuesOperationCompleted, userState);
        }
        
        private void OnSetItemValuesOperationCompleted(object arg) {
            if ((this.SetItemValuesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetItemValuesCompleted(this, new SetItemValuesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StartWorkflow", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BPMServiceResult StartWorkflow(string workflowCode, string userCode, bool finishStart, DataItemParam[] paramValues) {
            object[] results = this.Invoke("StartWorkflow", new object[] {
                        workflowCode,
                        userCode,
                        finishStart,
                        paramValues});
            return ((BPMServiceResult)(results[0]));
        }
        
        /// <remarks/>
        public void StartWorkflowAsync(string workflowCode, string userCode, bool finishStart, DataItemParam[] paramValues) {
            this.StartWorkflowAsync(workflowCode, userCode, finishStart, paramValues, null);
        }
        
        /// <remarks/>
        public void StartWorkflowAsync(string workflowCode, string userCode, bool finishStart, DataItemParam[] paramValues, object userState) {
            if ((this.StartWorkflowOperationCompleted == null)) {
                this.StartWorkflowOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStartWorkflowOperationCompleted);
            }
            this.InvokeAsync("StartWorkflow", new object[] {
                        workflowCode,
                        userCode,
                        finishStart,
                        paramValues}, this.StartWorkflowOperationCompleted, userState);
        }
        
        private void OnStartWorkflowOperationCompleted(object arg) {
            if ((this.StartWorkflowCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StartWorkflowCompleted(this, new StartWorkflowCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/postHttp", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string postHttp(string SchemaCode, string instanceid) {
            object[] results = this.Invoke("postHttp", new object[] {
                        SchemaCode,
                        instanceid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void postHttpAsync(string SchemaCode, string instanceid) {
            this.postHttpAsync(SchemaCode, instanceid, null);
        }
        
        /// <remarks/>
        public void postHttpAsync(string SchemaCode, string instanceid, object userState) {
            if ((this.postHttpOperationCompleted == null)) {
                this.postHttpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpostHttpOperationCompleted);
            }
            this.InvokeAsync("postHttp", new object[] {
                        SchemaCode,
                        instanceid}, this.postHttpOperationCompleted, userState);
        }
        
        private void OnpostHttpOperationCompleted(object arg) {
            if ((this.postHttpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.postHttpCompleted(this, new postHttpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class Authentication : System.Web.Services.Protocols.SoapHeader {
        
        private string userCodeField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string UserCode {
            get {
                return this.userCodeField;
            }
            set {
                this.userCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BPMServiceResult {
        
        private bool successField;
        
        private string instanceIDField;
        
        private string messageField;
        
        private string workItemIDField;
        
        private string workItemUrlField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string InstanceID {
            get {
                return this.instanceIDField;
            }
            set {
                this.instanceIDField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string WorkItemID {
            get {
                return this.workItemIDField;
            }
            set {
                this.workItemIDField = value;
            }
        }
        
        /// <remarks/>
        public string WorkItemUrl {
            get {
                return this.workItemUrlField;
            }
            set {
                this.workItemUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DataItemParam {
        
        private string itemNameField;
        
        private object itemValueField;
        
        /// <remarks/>
        public string ItemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
            }
        }
        
        /// <remarks/>
        public object ItemValue {
            get {
                return this.itemValueField;
            }
            set {
                this.itemValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void BizAutoAssignCompletedEventHandler(object sender, BizAutoAssignCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BizAutoAssignCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BizAutoAssignCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void BizAutoAssignHistoryCompletedEventHandler(object sender, BizAutoAssignHistoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BizAutoAssignHistoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BizAutoAssignHistoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void cancelInstanceDataCompletedEventHandler(object sender, cancelInstanceDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelInstanceDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelInstanceDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void updateInstanceDataCompletedEventHandler(object sender, updateInstanceDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateInstanceDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateInstanceDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void finishedInstanceCompletedEventHandler(object sender, finishedInstanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class finishedInstanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal finishedInstanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void postDZJRCompletedEventHandler(object sender, postDZJRCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class postDZJRCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal postDZJRCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void StartWorkFlowWidthValuesCompletedEventHandler(object sender, StartWorkFlowWidthValuesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StartWorkFlowWidthValuesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StartWorkFlowWidthValuesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void updateWorkFlowDataCompletedEventHandler(object sender, updateWorkFlowDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateWorkFlowDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateWorkFlowDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SetSigleItemValuesCompletedEventHandler(object sender, SetSigleItemValuesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetSigleItemValuesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetSigleItemValuesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SetItemValuesCompletedEventHandler(object sender, SetItemValuesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetItemValuesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetItemValuesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void StartWorkflowCompletedEventHandler(object sender, StartWorkflowCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StartWorkflowCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StartWorkflowCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BPMServiceResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BPMServiceResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void postHttpCompletedEventHandler(object sender, postHttpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class postHttpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal postHttpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591