//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace Polling.PollingWebService135 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PollingWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class PollingWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DistributorPollingOperationCompleted;
        
        private System.Threading.SendOrPostCallback CJHPollingOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreditPollingOperationCompleted;
        
        private System.Threading.SendOrPostCallback BillWflxOperationCompleted;
        
        private System.Threading.SendOrPostCallback BillCgfxrOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMessagePollingOperationCompleted;
        
        private System.Threading.SendOrPostCallback CAPPollingOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMessageCWFKPollingOperationCompleted;
        
        private System.Threading.SendOrPostCallback dealerInfoSUMMARYOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PollingWebService() {
            this.Url = global::Polling.Properties.Settings.Default.Polling_PollingWebService135_PollingWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DistributorPollingCompletedEventHandler DistributorPollingCompleted;
        
        /// <remarks/>
        public event CJHPollingCompletedEventHandler CJHPollingCompleted;
        
        /// <remarks/>
        public event CreditPollingCompletedEventHandler CreditPollingCompleted;
        
        /// <remarks/>
        public event BillWflxCompletedEventHandler BillWflxCompleted;
        
        /// <remarks/>
        public event BillCgfxrCompletedEventHandler BillCgfxrCompleted;
        
        /// <remarks/>
        public event SendMessagePollingCompletedEventHandler SendMessagePollingCompleted;
        
        /// <remarks/>
        public event CAPPollingCompletedEventHandler CAPPollingCompleted;
        
        /// <remarks/>
        public event SendMessageCWFKPollingCompletedEventHandler SendMessageCWFKPollingCompleted;
        
        /// <remarks/>
        public event dealerInfoSUMMARYCompletedEventHandler dealerInfoSUMMARYCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DistributorPolling", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DistributorPolling() {
            this.Invoke("DistributorPolling", new object[0]);
        }
        
        /// <remarks/>
        public void DistributorPollingAsync() {
            this.DistributorPollingAsync(null);
        }
        
        /// <remarks/>
        public void DistributorPollingAsync(object userState) {
            if ((this.DistributorPollingOperationCompleted == null)) {
                this.DistributorPollingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDistributorPollingOperationCompleted);
            }
            this.InvokeAsync("DistributorPolling", new object[0], this.DistributorPollingOperationCompleted, userState);
        }
        
        private void OnDistributorPollingOperationCompleted(object arg) {
            if ((this.DistributorPollingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DistributorPollingCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CJHPolling", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CJHPolling() {
            this.Invoke("CJHPolling", new object[0]);
        }
        
        /// <remarks/>
        public void CJHPollingAsync() {
            this.CJHPollingAsync(null);
        }
        
        /// <remarks/>
        public void CJHPollingAsync(object userState) {
            if ((this.CJHPollingOperationCompleted == null)) {
                this.CJHPollingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCJHPollingOperationCompleted);
            }
            this.InvokeAsync("CJHPolling", new object[0], this.CJHPollingOperationCompleted, userState);
        }
        
        private void OnCJHPollingOperationCompleted(object arg) {
            if ((this.CJHPollingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CJHPollingCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreditPolling", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreditPolling() {
            this.Invoke("CreditPolling", new object[0]);
        }
        
        /// <remarks/>
        public void CreditPollingAsync() {
            this.CreditPollingAsync(null);
        }
        
        /// <remarks/>
        public void CreditPollingAsync(object userState) {
            if ((this.CreditPollingOperationCompleted == null)) {
                this.CreditPollingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreditPollingOperationCompleted);
            }
            this.InvokeAsync("CreditPolling", new object[0], this.CreditPollingOperationCompleted, userState);
        }
        
        private void OnCreditPollingOperationCompleted(object arg) {
            if ((this.CreditPollingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreditPollingCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BillWflx", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void BillWflx() {
            this.Invoke("BillWflx", new object[0]);
        }
        
        /// <remarks/>
        public void BillWflxAsync() {
            this.BillWflxAsync(null);
        }
        
        /// <remarks/>
        public void BillWflxAsync(object userState) {
            if ((this.BillWflxOperationCompleted == null)) {
                this.BillWflxOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBillWflxOperationCompleted);
            }
            this.InvokeAsync("BillWflx", new object[0], this.BillWflxOperationCompleted, userState);
        }
        
        private void OnBillWflxOperationCompleted(object arg) {
            if ((this.BillWflxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BillWflxCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BillCgfxr", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void BillCgfxr() {
            this.Invoke("BillCgfxr", new object[0]);
        }
        
        /// <remarks/>
        public void BillCgfxrAsync() {
            this.BillCgfxrAsync(null);
        }
        
        /// <remarks/>
        public void BillCgfxrAsync(object userState) {
            if ((this.BillCgfxrOperationCompleted == null)) {
                this.BillCgfxrOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBillCgfxrOperationCompleted);
            }
            this.InvokeAsync("BillCgfxr", new object[0], this.BillCgfxrOperationCompleted, userState);
        }
        
        private void OnBillCgfxrOperationCompleted(object arg) {
            if ((this.BillCgfxrCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BillCgfxrCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendMessagePolling", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendMessagePolling() {
            this.Invoke("SendMessagePolling", new object[0]);
        }
        
        /// <remarks/>
        public void SendMessagePollingAsync() {
            this.SendMessagePollingAsync(null);
        }
        
        /// <remarks/>
        public void SendMessagePollingAsync(object userState) {
            if ((this.SendMessagePollingOperationCompleted == null)) {
                this.SendMessagePollingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMessagePollingOperationCompleted);
            }
            this.InvokeAsync("SendMessagePolling", new object[0], this.SendMessagePollingOperationCompleted, userState);
        }
        
        private void OnSendMessagePollingOperationCompleted(object arg) {
            if ((this.SendMessagePollingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMessagePollingCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CAPPolling", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CAPPolling() {
            this.Invoke("CAPPolling", new object[0]);
        }
        
        /// <remarks/>
        public void CAPPollingAsync() {
            this.CAPPollingAsync(null);
        }
        
        /// <remarks/>
        public void CAPPollingAsync(object userState) {
            if ((this.CAPPollingOperationCompleted == null)) {
                this.CAPPollingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCAPPollingOperationCompleted);
            }
            this.InvokeAsync("CAPPolling", new object[0], this.CAPPollingOperationCompleted, userState);
        }
        
        private void OnCAPPollingOperationCompleted(object arg) {
            if ((this.CAPPollingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CAPPollingCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendMessageCWFKPolling", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendMessageCWFKPolling() {
            this.Invoke("SendMessageCWFKPolling", new object[0]);
        }
        
        /// <remarks/>
        public void SendMessageCWFKPollingAsync() {
            this.SendMessageCWFKPollingAsync(null);
        }
        
        /// <remarks/>
        public void SendMessageCWFKPollingAsync(object userState) {
            if ((this.SendMessageCWFKPollingOperationCompleted == null)) {
                this.SendMessageCWFKPollingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMessageCWFKPollingOperationCompleted);
            }
            this.InvokeAsync("SendMessageCWFKPolling", new object[0], this.SendMessageCWFKPollingOperationCompleted, userState);
        }
        
        private void OnSendMessageCWFKPollingOperationCompleted(object arg) {
            if ((this.SendMessageCWFKPollingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMessageCWFKPollingCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dealerInfoSUMMARY", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void dealerInfoSUMMARY() {
            this.Invoke("dealerInfoSUMMARY", new object[0]);
        }
        
        /// <remarks/>
        public void dealerInfoSUMMARYAsync() {
            this.dealerInfoSUMMARYAsync(null);
        }
        
        /// <remarks/>
        public void dealerInfoSUMMARYAsync(object userState) {
            if ((this.dealerInfoSUMMARYOperationCompleted == null)) {
                this.dealerInfoSUMMARYOperationCompleted = new System.Threading.SendOrPostCallback(this.OndealerInfoSUMMARYOperationCompleted);
            }
            this.InvokeAsync("dealerInfoSUMMARY", new object[0], this.dealerInfoSUMMARYOperationCompleted, userState);
        }
        
        private void OndealerInfoSUMMARYOperationCompleted(object arg) {
            if ((this.dealerInfoSUMMARYCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.dealerInfoSUMMARYCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DistributorPollingCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CJHPollingCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CreditPollingCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void BillWflxCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void BillCgfxrCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SendMessagePollingCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CAPPollingCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SendMessageCWFKPollingCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void dealerInfoSUMMARYCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591